# Form implementation generated from reading ui file '/home/lukash/Projects/DMTL/assets/dialog_info.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ServerInfoDialog(object):
    def setupUi(self, ServerInfoDialog):
        ServerInfoDialog.setObjectName("ServerInfoDialog")
        ServerInfoDialog.resize(426, 563)
        self.verticalLayout = QtWidgets.QVBoxLayout(ServerInfoDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_browser = QtWidgets.QTextBrowser(parent=ServerInfoDialog)
        self.info_browser.setReadOnly(True)
        self.info_browser.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.info_browser.setObjectName("info_browser")
        self.verticalLayout.addWidget(self.info_browser)
        self.label_modlist = QtWidgets.QLabel(parent=ServerInfoDialog)
        self.label_modlist.setObjectName("label_modlist")
        self.verticalLayout.addWidget(self.label_modlist)
        self.list_mods = QtWidgets.QListWidget(parent=ServerInfoDialog)
        self.list_mods.setObjectName("list_mods")
        self.verticalLayout.addWidget(self.list_mods)
        self.btn_copy_ip = QtWidgets.QPushButton(parent=ServerInfoDialog)
        self.btn_copy_ip.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_copy_ip.setObjectName("btn_copy_ip")
        self.verticalLayout.addWidget(self.btn_copy_ip)

        self.retranslateUi(ServerInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(ServerInfoDialog)

    def retranslateUi(self, ServerInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        ServerInfoDialog.setWindowTitle(_translate("ServerInfoDialog", "Server Info"))
        self.info_browser.setStyleSheet(_translate("ServerInfoDialog", "background-color: transparent; border: none;"))
        self.label_modlist.setText(_translate("ServerInfoDialog", "<b>Mod List:</b>"))
        self.btn_copy_ip.setText(_translate("ServerInfoDialog", "📋 Copy Modlist"))
