name: Build Launcher

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Inject version from tag
      shell: bash
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "__version__ = '$VERSION'" > version.py
        else
          echo "__version__ = 'dev'" > version.py
        fi

    - name: Install dependencies and build Rust module
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        maturin build --release -m rust_src/Cargo.toml --out wheels
        pip install --no-index --find-links=wheels dmtl_core

    - name: Build on Linux
      if: runner.os == 'Linux'
      run: |
        pyinstaller --noconfirm --onedir --windowed --icon "assets/icon.png" --add-data "assets:assets" --add-data "locales:locales" --add-data "steam_appid.txt:." --add-data "libsteam_api.so:." --add-data "SteamworksPy.so:." --name "DMTL-Linux" launcher.py
        rm -f dist/DMTL-Linux/_internal/libxkbcommon.so.0
        cd dist
        tar -czvf DMTL-Linux.tar.gz DMTL-Linux/

    - name: Build on Windows
      if: runner.os == 'Windows'
      run: |
        pyinstaller --noconfirm --onedir --windowed --icon "assets/icon.png" --add-data "assets;assets" --add-data "locales;locales" --add-data "steam_appid.txt;." --add-data "steam_api64.dll;." --add-data "SteamworksPy64.dll;." --name "DMTL-Windows" launcher.py
        Compress-Archive -Path dist\DMTL-Windows -DestinationPath dist\DMTL-Windows.zip

    - name: Upload Linux Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: DMTL-Linux
        path: dist/DMTL-Linux.tar.gz

    - name: Upload Windows Artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: DMTL-Windows
        path: dist\DMTL-Windows.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/DMTL-Linux/DMTL-Linux.tar.gz
            artifacts/DMTL-Windows/DMTL-Windows.zip

  aur-publish:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare PKGBUILD and update Checksum
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^pkgver=.*/pkgver=$VERSION/" PKGBUILD

          wget https://github.com/${{ github.repository }}/releases/download/v$VERSION/DMTL-Linux.tar.gz
          CHECKSUM=$(sha256sum DMTL-Linux.tar.gz | awk '{print $1}')

          sed -i "s/^sha256sums=.*/sha256sums=('$CHECKSUM')/" PKGBUILD

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v3.0.1
        with:
          pkgname: dmtl-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ github.repository_owner }}
          commit_email: lukash@aur.archlinux.org
          ssh_private_key: ${{ secrets.AUR_PRIVATE_KEY }}
          commit_message: "Auto-release version ${{ github.ref_name }}"
          force_push: true
